Hello .... This file contains the string functions..

This is used for to know how Clone command is working for very first time for Pull Request............

  Again, I am checking how the Clone command is working for Pull. If I updated 2 commits at a time...............
Again, I am checking how the Clone command is working for Pull 1. If I updated 2 commits at a time...............
  
Again, I am checking how the Clone command is working for Fetch. If I updated 2 commits at a time...............

I am writing this line to know,what is the clone regular eeror came.
This can be done by SSH key class.
